# Generated by Django 4.1.5 on 2023-02-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_book_cover_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
