# Generated by Django 4.1.5 on 2023-02-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Category',
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
